-- MySQL Script generated by MySQL Workbench
-- Mon Nov 22 21:25:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cuentomislukas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuentomislukas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuentomislukas` DEFAULT CHARACTER SET utf8 ;
USE `cuentomislukas` ;

-- -----------------------------------------------------
-- Table `cuentomislukas`.`ahorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`ahorro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoAhorro` VARCHAR(25) NULL DEFAULT NULL,
  `idCategoriaAhorro` INT(11) NULL DEFAULT NULL,
  `fechaAhorro` DATE NULL DEFAULT NULL,
  `valorAhorro` DOUBLE NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`categoria_egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`categoria_egresos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`categoria_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`categoria_ingresos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`genero` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `idGenero` INT(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nombreUsuario` VARCHAR(30) NOT NULL,
  `claveAcceso` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `idRol` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_genero_id_idx` (`idGenero` ASC) VISIBLE,
  INDEX `fk_usuarios_rol_id_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_genero_id`
    FOREIGN KEY (`idGenero`)
    REFERENCES `cuentomislukas`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_rol_id`
    FOREIGN KEY (`idRol`)
    REFERENCES `cuentomislukas`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`egreso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoEgreso` VARCHAR(25) NOT NULL,
  `idCategoriaEgreso` INT(11) NOT NULL,
  `fechaEgreso` DATE NOT NULL,
  `valorEgreso` DOUBLE NOT NULL,
  `descripcion` VARCHAR(60) NULL DEFAULT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_egreso_categoria_id_idx` (`idCategoriaEgreso` ASC) VISIBLE,
  INDEX `fk_egreso_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_egreso_categoria_id`
    FOREIGN KEY (`idCategoriaEgreso`)
    REFERENCES `cuentomislukas`.`categoria_egresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_egreso_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cuentomislukas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`ingreso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoIngreso` VARCHAR(20) NOT NULL,
  `idCategoriaIngreso` INT(11) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `valorIngreso` DOUBLE NOT NULL,
  `descripcion` VARCHAR(60) NULL DEFAULT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingreso_categoria_id_idx` (`idCategoriaIngreso` ASC) VISIBLE,
  INDEX `fk_ingreso_usuarios_id_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_categoria_id`
    FOREIGN KEY (`idCategoriaIngreso`)
    REFERENCES `cuentomislukas`.`categoria_ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_usuarios_id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cuentomislukas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`metas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `valorParcial` DOUBLE NOT NULL,
  `fechaObjetiva` DATE NOT NULL,
  `fechaCalculada` DATE NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metas_usuario_id_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_metas_usuario_id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cuentomislukas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`modulo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`operaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `idModulo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operaciones_modulo_id_idx` (`idModulo` ASC) VISIBLE,
  CONSTRAINT `fk_operaciones_modulo_id`
    FOREIGN KEY (`idModulo`)
    REFERENCES `cuentomislukas`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cuentomislukas`.`rol_operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuentomislukas`.`rol_operacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idRol` INT(11) NOT NULL,
  `idOperacion` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roloperacion_rol_id_idx` (`idRol` ASC) VISIBLE,
  INDEX `fk_roloperacion_operaciones_id_idx` (`idOperacion` ASC) VISIBLE,
  CONSTRAINT `fk_roloperacion_operaciones_id`
    FOREIGN KEY (`idOperacion`)
    REFERENCES `cuentomislukas`.`operaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roloperacion_rol_id`
    FOREIGN KEY (`idRol`)
    REFERENCES `cuentomislukas`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
